sudo: false

language: node_js
node_js:
  - 6
  - node
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_script:
  - make deps
  - make lint
notifications:
  email:
    - phihag@phihag.de

