language: node_js
node_js:
  - "4.1"
  - 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
install:
  - make deps
before_script:
  - make lint
notifications:
  email:
    - phihag@phihag.de

